# Lotus Per-App Configuration
# 0 = Off, 1 = Uinput (Smooth), 2 = Uinput (Slow), 3 = Uinput (Hardcore), 4 = Surrounding Text, 5 = Preedit, 6 = Emoji Picker
soffice=3
libreoffice-startcenter=1
firefox=1
google-chrome=3
claude-desktop=1
antigravity=3
Alacritty=1
